# Generated by Django 4.0.5 on 2022-06-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userprofilemodel_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_profession',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
