# Generated by Django 4.0.5 on 2022-06-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userprofilemodel_user_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user_profession',
            field=models.CharField(max_length=200),
        ),
    ]
