# Generated by Django 4.0.5 on 2022-06-17 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_userprofilemodel_user_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_github',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_profession',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_twitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user_youtube',
            new_name='youtube',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='skills',
            field=models.ManyToManyField(to='Users.skillsmodel'),
        ),
    ]
