# Generated by Django 4.0.5 on 2022-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_userprofilemodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
