# Generated by Django 4.0.5 on 2022-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_skillsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
