# Generated by Django 4.0.5 on 2022-06-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_skillsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, default='Images/User/user.png', upload_to='User/'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='youtube',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
