# Generated by Django 4.0.5 on 2022-06-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_userprofilemodel_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='owner',
            field=models.ManyToManyField(to='Users.userprofilemodel'),
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='skills',
            field=models.ManyToManyField(to='Users.skillsmodel'),
        ),
    ]
