# Generated by Django 4.0.5 on 2022-06-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_skillsmodel_owner_remove_userprofilemodel_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsmodel',
            name='owner',
        ),
    ]
