# Generated by Django 4.0.5 on 2022-06-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_remove_skillsmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.userprofilemodel'),
        ),
    ]
