# Generated by Django 4.0.5 on 2022-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_skillsmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsmodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='owner',
            field=models.ManyToManyField(to='Users.userprofilemodel'),
        ),
    ]
