# Generated by Django 4.0.5 on 2022-06-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_remove_skillsmodel_owner_skillsmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsmodel',
            name='owner',
        ),
    ]
