# Generated by Django 4.0.5 on 2022-06-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='ProjectsModel',
        ),
    ]
