# Generated by Django 4.0.5 on 2022-06-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0002_rename_projects_projectsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsmodel',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='projectsmodel',
            old_name='title',
            new_name='project_title',
        ),
    ]
