# Generated by Django 4.0.5 on 2022-06-13 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0003_rename_description_projectsmodel_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('review_body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProjects.projectsmodel')),
            ],
        ),
    ]
