# Generated by Django 4.0.5 on 2022-06-13 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0004_reviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTagsModel',
            fields=[
                ('skill_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='total_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='project_skill_tag',
            field=models.ManyToManyField(blank=True, to='UserProjects.skilltagsmodel'),
        ),
    ]
