# Generated by Django 4.0.5 on 2022-06-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0005_skilltagsmodel_projectsmodel_total_votes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsmodel',
            old_name='project_skill_tag',
            new_name='project_skills',
        ),
    ]
