# Generated by Django 4.0.5 on 2022-06-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0007_alter_projectsmodel_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_skills',
            field=models.ManyToManyField(blank=True, to='UserProjects.skilltagsmodel'),
        ),
    ]
