# Generated by Django 4.0.5 on 2022-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0011_alter_projectsmodel_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='project_image',
            field=models.ImageField(blank=True, default='Images/Project/default.jpg', null=True, upload_to='projects/'),
        ),
    ]
