# Generated by Django 4.0.5 on 2022-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0012_projectsmodel_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_image',
            field=models.ImageField(blank=True, default='Images/Project/default.jpg', null=True, upload_to=''),
        ),
    ]
