# Generated by Django 4.0.5 on 2022-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0013_alter_projectsmodel_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_image',
            field=models.ImageField(blank=True, default='Images/Project/default.jpg', null=True, upload_to='Images/Project/'),
        ),
    ]
