# Generated by Django 4.0.5 on 2022-06-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userprofilemodel_user_image'),
        ('UserProjects', '0014_alter_projectsmodel_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='project_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.userprofilemodel'),
        ),
    ]
