# Generated by Django 4.0.5 on 2022-06-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userprofilemodel_user_image'),
        ('UserProjects', '0015_projectsmodel_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofilemodel'),
        ),
    ]
