# Generated by Django 4.0.5 on 2022-06-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0016_alter_projectsmodel_project_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='ProjectReviewModel',
        ),
        migrations.RenameModel(
            old_name='SkillTagsModel',
            new_name='ProjectSkillTagsModel',
        ),
    ]
