# Generated by Django 4.0.5 on 2022-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_skillsmodel_description'),
        ('UserProjects', '0017_rename_reviewmodel_projectreviewmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='project_owner',
            field=models.ManyToManyField(to='Users.userprofilemodel'),
        ),
    ]
