# Generated by Django 4.0.5 on 2022-06-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_skillsmodel_description'),
        ('UserProjects', '0018_remove_projectsmodel_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='project_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.userprofilemodel'),
        ),
    ]
