# Generated by Django 4.0.5 on 2022-06-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_skillsmodel_description'),
        ('UserProjects', '0019_remove_projectsmodel_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreviewmodel',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.userprofilemodel'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
    ]
