# Generated by Django 4.0.5 on 2022-06-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_skillsmodel_description'),
        ('UserProjects', '0020_projectreviewmodel_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreviewmodel',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofilemodel'),
        ),
    ]
