# Generated by Django 4.0.5 on 2022-06-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0021_alter_projectreviewmodel_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_image',
            field=models.ImageField(blank=True, default='Images/Project/default.jpg', upload_to='Images/Project/'),
        ),
    ]
