# Generated by Django 4.0.5 on 2022-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_skillsmodel_owner'),
        ('UserProjects', '0023_remove_projectsmodel_project_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='project_skills',
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='project_skills',
            field=models.ManyToManyField(to='Users.skillsmodel'),
        ),
    ]
