# Generated by Django 4.0.5 on 2022-06-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjects', '0024_remove_projectsmodel_project_skills_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSkillTagsModel',
        ),
    ]
